version: "2"
run:
  tests: true
linters:
  settings:
    revive:
      rules:
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#unexported-return
        - name: unexported-return
          severity: warning
          disabled: true
          exclude: [ "" ]
  enable:
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
